//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopUI.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auth", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class Auth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.BookResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.AllBooksResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.OrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.OrdersByUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.UserResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class BookResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.Book bookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.Book book {
            get {
                return this.bookField;
            }
            set {
                if ((object.ReferenceEquals(this.bookField, value) != true)) {
                    this.bookField = value;
                    this.RaisePropertyChanged("book");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllBooksResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class AllBooksResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.Book[] booksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.Book[] books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class OrderResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.OrderData orderDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.OrderData orderData {
            get {
                return this.orderDataField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDataField, value) != true)) {
                    this.orderDataField = value;
                    this.RaisePropertyChanged("orderData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdersByUser", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class OrdersByUser : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.OrderData[] orderDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.OrderData[] orderData {
            get {
                return this.orderDataField;
            }
            set {
                if ((object.ReferenceEquals(this.orderDataField, value) != true)) {
                    this.orderDataField = value;
                    this.RaisePropertyChanged("orderData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class UserResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.User userField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool deletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                if ((this.deletedField.Equals(value) != true)) {
                    this.deletedField = value;
                    this.RaisePropertyChanged("deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int costField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool deletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cost {
            get {
                return this.costField;
            }
            set {
                if ((this.costField.Equals(value) != true)) {
                    this.costField = value;
                    this.RaisePropertyChanged("cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                if ((this.deletedField.Equals(value) != true)) {
                    this.deletedField = value;
                    this.RaisePropertyChanged("deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderData", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class OrderData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.Book[] booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.Book[] books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPayment {
            get {
                return this.totalPaymentField;
            }
            set {
                if ((this.totalPaymentField.Equals(value) != true)) {
                    this.totalPaymentField = value;
                    this.RaisePropertyChanged("totalPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderRequest", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class OrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPayment {
            get {
                return this.totalPaymentField;
            }
            set {
                if ((this.totalPaymentField.Equals(value) != true)) {
                    this.totalPaymentField = value;
                    this.RaisePropertyChanged("totalPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPayment {
            get {
                return this.totalPaymentField;
            }
            set {
                if ((this.totalPaymentField.Equals(value) != true)) {
                    this.totalPaymentField = value;
                    this.RaisePropertyChanged("totalPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRestService")]
    public interface IRestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/Auth", ReplyAction="http://tempuri.org/IRestService/AuthResponse")]
        ShopUI.ServiceReference.UserResponse Auth(ShopUI.ServiceReference.Auth data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/Auth", ReplyAction="http://tempuri.org/IRestService/AuthResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.UserResponse> AuthAsync(ShopUI.ServiceReference.Auth data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetUser", ReplyAction="http://tempuri.org/IRestService/GetUserResponse")]
        ShopUI.ServiceReference.UserResponse GetUser(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetUser", ReplyAction="http://tempuri.org/IRestService/GetUserResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.UserResponse> GetUserAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteUser", ReplyAction="http://tempuri.org/IRestService/DeleteUserResponse")]
        string DeleteUser(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteUser", ReplyAction="http://tempuri.org/IRestService/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreUser", ReplyAction="http://tempuri.org/IRestService/RestoreUserResponse")]
        string RestoreUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreUser", ReplyAction="http://tempuri.org/IRestService/RestoreUserResponse")]
        System.Threading.Tasks.Task<string> RestoreUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewUser", ReplyAction="http://tempuri.org/IRestService/NewUserResponse")]
        string NewUser(ShopUI.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewUser", ReplyAction="http://tempuri.org/IRestService/NewUserResponse")]
        System.Threading.Tasks.Task<string> NewUserAsync(ShopUI.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateUser", ReplyAction="http://tempuri.org/IRestService/UpdateUserResponse")]
        string UpdateUser(ShopUI.ServiceReference.User updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateUser", ReplyAction="http://tempuri.org/IRestService/UpdateUserResponse")]
        System.Threading.Tasks.Task<string> UpdateUserAsync(ShopUI.ServiceReference.User updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetBook", ReplyAction="http://tempuri.org/IRestService/GetBookResponse")]
        ShopUI.ServiceReference.BookResponse GetBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetBook", ReplyAction="http://tempuri.org/IRestService/GetBookResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.BookResponse> GetBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/AllBooks", ReplyAction="http://tempuri.org/IRestService/AllBooksResponse")]
        ShopUI.ServiceReference.AllBooksResponse AllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/AllBooks", ReplyAction="http://tempuri.org/IRestService/AllBooksResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.AllBooksResponse> AllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteBook", ReplyAction="http://tempuri.org/IRestService/DeleteBookResponse")]
        string DeleteBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteBook", ReplyAction="http://tempuri.org/IRestService/DeleteBookResponse")]
        System.Threading.Tasks.Task<string> DeleteBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreBook", ReplyAction="http://tempuri.org/IRestService/RestoreBookResponse")]
        string RestoreBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreBook", ReplyAction="http://tempuri.org/IRestService/RestoreBookResponse")]
        System.Threading.Tasks.Task<string> RestoreBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewBook", ReplyAction="http://tempuri.org/IRestService/NewBookResponse")]
        ShopUI.ServiceReference.Book NewBook(ShopUI.ServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewBook", ReplyAction="http://tempuri.org/IRestService/NewBookResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.Book> NewBookAsync(ShopUI.ServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateBook", ReplyAction="http://tempuri.org/IRestService/UpdateBookResponse")]
        string UpdateBook(ShopUI.ServiceReference.Book updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateBook", ReplyAction="http://tempuri.org/IRestService/UpdateBookResponse")]
        System.Threading.Tasks.Task<string> UpdateBookAsync(ShopUI.ServiceReference.Book updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetOrder", ReplyAction="http://tempuri.org/IRestService/GetOrderResponse")]
        ShopUI.ServiceReference.OrderResponse GetOrder(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetOrder", ReplyAction="http://tempuri.org/IRestService/GetOrderResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.OrderResponse> GetOrderAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetOrdersByUserId", ReplyAction="http://tempuri.org/IRestService/GetOrdersByUserIdResponse")]
        ShopUI.ServiceReference.OrdersByUser GetOrdersByUserId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetOrdersByUserId", ReplyAction="http://tempuri.org/IRestService/GetOrdersByUserIdResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.OrdersByUser> GetOrdersByUserIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/PayOrder", ReplyAction="http://tempuri.org/IRestService/PayOrderResponse")]
        string PayOrder(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/PayOrder", ReplyAction="http://tempuri.org/IRestService/PayOrderResponse")]
        System.Threading.Tasks.Task<string> PayOrderAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewOrder", ReplyAction="http://tempuri.org/IRestService/NewOrderResponse")]
        ShopUI.ServiceReference.Order NewOrder(ShopUI.ServiceReference.OrderRequest orderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewOrder", ReplyAction="http://tempuri.org/IRestService/NewOrderResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.Order> NewOrderAsync(ShopUI.ServiceReference.OrderRequest orderRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : ShopUI.ServiceReference.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<ShopUI.ServiceReference.IRestService>, ShopUI.ServiceReference.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShopUI.ServiceReference.UserResponse Auth(ShopUI.ServiceReference.Auth data) {
            return base.Channel.Auth(data);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.UserResponse> AuthAsync(ShopUI.ServiceReference.Auth data) {
            return base.Channel.AuthAsync(data);
        }
        
        public ShopUI.ServiceReference.UserResponse GetUser(string id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.UserResponse> GetUserAsync(string id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public string DeleteUser(string id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(string id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public string RestoreUser(string email) {
            return base.Channel.RestoreUser(email);
        }
        
        public System.Threading.Tasks.Task<string> RestoreUserAsync(string email) {
            return base.Channel.RestoreUserAsync(email);
        }
        
        public string NewUser(ShopUI.ServiceReference.User user) {
            return base.Channel.NewUser(user);
        }
        
        public System.Threading.Tasks.Task<string> NewUserAsync(ShopUI.ServiceReference.User user) {
            return base.Channel.NewUserAsync(user);
        }
        
        public string UpdateUser(ShopUI.ServiceReference.User updateData) {
            return base.Channel.UpdateUser(updateData);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserAsync(ShopUI.ServiceReference.User updateData) {
            return base.Channel.UpdateUserAsync(updateData);
        }
        
        public ShopUI.ServiceReference.BookResponse GetBook(string id) {
            return base.Channel.GetBook(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.BookResponse> GetBookAsync(string id) {
            return base.Channel.GetBookAsync(id);
        }
        
        public ShopUI.ServiceReference.AllBooksResponse AllBooks() {
            return base.Channel.AllBooks();
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.AllBooksResponse> AllBooksAsync() {
            return base.Channel.AllBooksAsync();
        }
        
        public string DeleteBook(string id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBookAsync(string id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public string RestoreBook(string id) {
            return base.Channel.RestoreBook(id);
        }
        
        public System.Threading.Tasks.Task<string> RestoreBookAsync(string id) {
            return base.Channel.RestoreBookAsync(id);
        }
        
        public ShopUI.ServiceReference.Book NewBook(ShopUI.ServiceReference.Book book) {
            return base.Channel.NewBook(book);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.Book> NewBookAsync(ShopUI.ServiceReference.Book book) {
            return base.Channel.NewBookAsync(book);
        }
        
        public string UpdateBook(ShopUI.ServiceReference.Book updateData) {
            return base.Channel.UpdateBook(updateData);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBookAsync(ShopUI.ServiceReference.Book updateData) {
            return base.Channel.UpdateBookAsync(updateData);
        }
        
        public ShopUI.ServiceReference.OrderResponse GetOrder(string id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.OrderResponse> GetOrderAsync(string id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public ShopUI.ServiceReference.OrdersByUser GetOrdersByUserId(string id) {
            return base.Channel.GetOrdersByUserId(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.OrdersByUser> GetOrdersByUserIdAsync(string id) {
            return base.Channel.GetOrdersByUserIdAsync(id);
        }
        
        public string PayOrder(string id) {
            return base.Channel.PayOrder(id);
        }
        
        public System.Threading.Tasks.Task<string> PayOrderAsync(string id) {
            return base.Channel.PayOrderAsync(id);
        }
        
        public ShopUI.ServiceReference.Order NewOrder(ShopUI.ServiceReference.OrderRequest orderRequest) {
            return base.Channel.NewOrder(orderRequest);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.Order> NewOrderAsync(ShopUI.ServiceReference.OrderRequest orderRequest) {
            return base.Channel.NewOrderAsync(orderRequest);
        }
    }
}
