//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopUI.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.BookResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.OrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShopUI.ServiceReference.UserResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class BookResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.Book BookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.Book Book {
            get {
                return this.BookField;
            }
            set {
                if ((object.ReferenceEquals(this.BookField, value) != true)) {
                    this.BookField = value;
                    this.RaisePropertyChanged("Book");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class OrderResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.OrderRequest OrderDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.OrderRequest OrderData {
            get {
                return this.OrderDataField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDataField, value) != true)) {
                    this.OrderDataField = value;
                    this.RaisePropertyChanged("OrderData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class UserResponse : ShopUI.ServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopUI.ServiceReference.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShopUI.ServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/TestService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cost {
            get {
                return this.CostField;
            }
            set {
                if ((this.CostField.Equals(value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderRequest", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class OrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPayment {
            get {
                return this.TotalPaymentField;
            }
            set {
                if ((this.TotalPaymentField.Equals(value) != true)) {
                    this.TotalPaymentField = value;
                    this.RaisePropertyChanged("TotalPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/TestService.Models")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPayment {
            get {
                return this.TotalPaymentField;
            }
            set {
                if ((this.TotalPaymentField.Equals(value) != true)) {
                    this.TotalPaymentField = value;
                    this.RaisePropertyChanged("TotalPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRestService")]
    public interface IRestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetUser", ReplyAction="http://tempuri.org/IRestService/GetUserResponse")]
        ShopUI.ServiceReference.UserResponse GetUser(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetUser", ReplyAction="http://tempuri.org/IRestService/GetUserResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.UserResponse> GetUserAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteUser", ReplyAction="http://tempuri.org/IRestService/DeleteUserResponse")]
        string DeleteUser(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteUser", ReplyAction="http://tempuri.org/IRestService/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreUser", ReplyAction="http://tempuri.org/IRestService/RestoreUserResponse")]
        string RestoreUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreUser", ReplyAction="http://tempuri.org/IRestService/RestoreUserResponse")]
        System.Threading.Tasks.Task<string> RestoreUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewUser", ReplyAction="http://tempuri.org/IRestService/NewUserResponse")]
        string NewUser(ShopUI.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewUser", ReplyAction="http://tempuri.org/IRestService/NewUserResponse")]
        System.Threading.Tasks.Task<string> NewUserAsync(ShopUI.ServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateUser", ReplyAction="http://tempuri.org/IRestService/UpdateUserResponse")]
        string UpdateUser(ShopUI.ServiceReference.User updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateUser", ReplyAction="http://tempuri.org/IRestService/UpdateUserResponse")]
        System.Threading.Tasks.Task<string> UpdateUserAsync(ShopUI.ServiceReference.User updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetBook", ReplyAction="http://tempuri.org/IRestService/GetBookResponse")]
        ShopUI.ServiceReference.BookResponse GetBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetBook", ReplyAction="http://tempuri.org/IRestService/GetBookResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.BookResponse> GetBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteBook", ReplyAction="http://tempuri.org/IRestService/DeleteBookResponse")]
        string DeleteBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/DeleteBook", ReplyAction="http://tempuri.org/IRestService/DeleteBookResponse")]
        System.Threading.Tasks.Task<string> DeleteBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreBook", ReplyAction="http://tempuri.org/IRestService/RestoreBookResponse")]
        string RestoreBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/RestoreBook", ReplyAction="http://tempuri.org/IRestService/RestoreBookResponse")]
        System.Threading.Tasks.Task<string> RestoreBookAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewBook", ReplyAction="http://tempuri.org/IRestService/NewBookResponse")]
        ShopUI.ServiceReference.Book NewBook(ShopUI.ServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewBook", ReplyAction="http://tempuri.org/IRestService/NewBookResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.Book> NewBookAsync(ShopUI.ServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateBook", ReplyAction="http://tempuri.org/IRestService/UpdateBookResponse")]
        string UpdateBook(ShopUI.ServiceReference.Book updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/UpdateBook", ReplyAction="http://tempuri.org/IRestService/UpdateBookResponse")]
        System.Threading.Tasks.Task<string> UpdateBookAsync(ShopUI.ServiceReference.Book updateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetOrder", ReplyAction="http://tempuri.org/IRestService/GetOrderResponse")]
        ShopUI.ServiceReference.OrderResponse GetOrder(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetOrder", ReplyAction="http://tempuri.org/IRestService/GetOrderResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.OrderResponse> GetOrderAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/PayOrder", ReplyAction="http://tempuri.org/IRestService/PayOrderResponse")]
        string PayOrder(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/PayOrder", ReplyAction="http://tempuri.org/IRestService/PayOrderResponse")]
        System.Threading.Tasks.Task<string> PayOrderAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewOrder", ReplyAction="http://tempuri.org/IRestService/NewOrderResponse")]
        ShopUI.ServiceReference.Order NewOrder(ShopUI.ServiceReference.OrderRequest orderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/NewOrder", ReplyAction="http://tempuri.org/IRestService/NewOrderResponse")]
        System.Threading.Tasks.Task<ShopUI.ServiceReference.Order> NewOrderAsync(ShopUI.ServiceReference.OrderRequest orderRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : ShopUI.ServiceReference.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<ShopUI.ServiceReference.IRestService>, ShopUI.ServiceReference.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShopUI.ServiceReference.UserResponse GetUser(string id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.UserResponse> GetUserAsync(string id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public string DeleteUser(string id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(string id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public string RestoreUser(string email) {
            return base.Channel.RestoreUser(email);
        }
        
        public System.Threading.Tasks.Task<string> RestoreUserAsync(string email) {
            return base.Channel.RestoreUserAsync(email);
        }
        
        public string NewUser(ShopUI.ServiceReference.User user) {
            return base.Channel.NewUser(user);
        }
        
        public System.Threading.Tasks.Task<string> NewUserAsync(ShopUI.ServiceReference.User user) {
            return base.Channel.NewUserAsync(user);
        }
        
        public string UpdateUser(ShopUI.ServiceReference.User updateData) {
            return base.Channel.UpdateUser(updateData);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserAsync(ShopUI.ServiceReference.User updateData) {
            return base.Channel.UpdateUserAsync(updateData);
        }
        
        public ShopUI.ServiceReference.BookResponse GetBook(string id) {
            return base.Channel.GetBook(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.BookResponse> GetBookAsync(string id) {
            return base.Channel.GetBookAsync(id);
        }
        
        public string DeleteBook(string id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBookAsync(string id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public string RestoreBook(string id) {
            return base.Channel.RestoreBook(id);
        }
        
        public System.Threading.Tasks.Task<string> RestoreBookAsync(string id) {
            return base.Channel.RestoreBookAsync(id);
        }
        
        public ShopUI.ServiceReference.Book NewBook(ShopUI.ServiceReference.Book book) {
            return base.Channel.NewBook(book);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.Book> NewBookAsync(ShopUI.ServiceReference.Book book) {
            return base.Channel.NewBookAsync(book);
        }
        
        public string UpdateBook(ShopUI.ServiceReference.Book updateData) {
            return base.Channel.UpdateBook(updateData);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBookAsync(ShopUI.ServiceReference.Book updateData) {
            return base.Channel.UpdateBookAsync(updateData);
        }
        
        public ShopUI.ServiceReference.OrderResponse GetOrder(string id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.OrderResponse> GetOrderAsync(string id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public string PayOrder(string id) {
            return base.Channel.PayOrder(id);
        }
        
        public System.Threading.Tasks.Task<string> PayOrderAsync(string id) {
            return base.Channel.PayOrderAsync(id);
        }
        
        public ShopUI.ServiceReference.Order NewOrder(ShopUI.ServiceReference.OrderRequest orderRequest) {
            return base.Channel.NewOrder(orderRequest);
        }
        
        public System.Threading.Tasks.Task<ShopUI.ServiceReference.Order> NewOrderAsync(ShopUI.ServiceReference.OrderRequest orderRequest) {
            return base.Channel.NewOrderAsync(orderRequest);
        }
    }
}
